#!/usr/bin/env ruby

# git://github.com/Shougo/neocomplcache.git
# git://github.com/marijnh/tern_for_vim.git

git_bundles = %w{
  git://github.com/elzr/vim-json.git
  git://github.com/scrooloose/nerdtree.git
  git://github.com/corntrace/bufexplorer.git
  git://github.com/scrooloose/syntastic.git
  git://github.com/vim-scripts/taglist.vim.git
  git://github.com/vim-scripts/vimwiki.git
  git://github.com/vim-scripts/TaskList.vim.git
  git://github.com/kchmck/vim-coffee-script.git
  git://github.com/groenewege/vim-less.git
  git://github.com/airblade/vim-gitgutter.git
  git://github.com/tpope/vim-fugitive.git
  git://github.com/ervandew/supertab.git
  git://github.com/mattn/emmet-vim.git
  git://github.com/vim-scripts/ScrollColors.git
  git://github.com/kien/ctrlp.vim.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }
